### ISSUE TITLE
denoise_fn的问题

### ISSUE THREAD

**Issue by laoxie521** [GuoLanqing/ShadowDiffusion#10]
你好我在ddpm的预测噪声部分，发现class GaussianDiffusion(nn.Module):
    def __init__(
        self,
        denoise_fn,
        image_size,
        channels=3,
        loss_type='l1',
        conditional=True,
        schedule_opt=None
    ):
初始化的denoise_fn是一个随机参数，但是后面引用它明显把他当成函数引用。我猜测这个应该引用了神经网络，但是好像确确实实没有进行定义。所以这个到底是什么？

**Comment by GuoLanqing** [comment]
`denoise_fn` is the denoising model. You can refer to lines 96-114 in `networks.py`.

**Comment by laoxie521** [comment]
thank you， i find out

**Comment by laoxie521** [comment]
thank you， i find out
