### ISSUE TITLE
about pretrained Uformer network

### ISSUE THREAD

**Issue by dgjung0220** [GuoLanqing/ShadowDiffusion#13]
Hello. I enjoyed reading your paper. However, it seems that the current code is not using the uformer pretrained network as described in the paper. Instead, it appears to be utilizing the res_map. Is it possible to achieve the same results by training in this manner? If so, it seems like the code has been updated in a direction that might be even better than the introduction in the paper.

**Comment by GuoLanqing** [comment]
Thanks for your interest. Have sent to your email.

**Comment by yanmengyi** [comment]
Hello,I have the same question, can I have this email too?

**Comment by GuoLanqing** [comment]
Sure, please send your email to me. Thanks.

**Comment by yanmengyi** [comment]
1799183056@qq.com. Thank you so much !!!

**Comment by gejutaixiao22** [comment]
Hello ,I have the same question, can I have this email too?  My email is 1102565998@qq.com.Thank you very much

**Comment by Henry-Bi** [comment]
Hello,I have the same question too. My email is bihengyue@stu.ouc.edu.cn. Thank you!

**Comment by finnn00** [comment]
Hey,  can I have this email too? My email is finn951017@outlook.com
Thank you!

**Comment by Henry-Bi** [comment]
Hello, I also have the same question and hope to receive your response. My email is: bihengyue@stu.ouc.edu.cn. I look forward to your email!

**Comment by BlackJoke76** [comment]
Hello ,I have the same question, can I have this email too? My email is 905233173@qq.com.Thank you very much
