### ISSUE TITLE
Some questions for the  Figure2.

### ISSUE THREAD

**Issue by hongsheng-Z** [GuoLanqing/ShadowDiffusion#14]
Thank you for this excellent work. However, I have a little confusion about the `X_T`  in Fig2.  I don't understand what exactly `X_T` is used for, where does it come from (add noise to y, or produced by forward diffusion)? It seems that the corresponding module to handle it cannot be found in the code. 
Looking forward to your reply, thank you！

**Comment by GuoLanqing** [comment]
`x_T` is random noise. Please refer to
https://github.com/GuoLanqing/ShadowDiffusion/blob/60095b2d804fe64909b975847577326044e15b51/model/sr3_modules/diffusion.py#L190C1-L191C1
