### ISSUE TITLE
more detailed mask images

### ISSUE THREAD

**Issue by yanmengyi** [GuoLanqing/ShadowDiffusion#16]
Hello author, thank you very much for sharing the code of your paper. Your method is very innovative, and I have been learning from it. I have a small question: how can I modify the code to obtain "more detailed mask images" as mentioned in the paper? How can I make the code output these images?

**Comment by sunwarm2001** [comment]
Hello, I have the same doubts, maybe we can talk with each other more deeply, here is my email: 1015942446@qq.com

**Comment by sunwarm2001** [comment]
Hello, I have the same doubts. Have you solved the problem?
Maybe we can talk with each other, here is my email: 1015942446@qq.com
