### ISSUE TITLE
Error while training with ISTD dataset

### ISSUE THREAD

**Issue by gejutaixiao22** [GuoLanqing/ShadowDiffusion#18]
23-12-11 08:20:46.337 - INFO: Model [DDPM] is created.
23-12-11 08:20:46.337 - INFO: Initial Model Finished
23-12-11 08:21:49.840 - INFO: <epoch:  1, iter:     100> l_pix: 3.2691e-01 
23-12-11 08:22:51.153 - INFO: <epoch:  2, iter:     200> l_pix: 2.1998e-01 
23-12-11 08:23:46.322 - INFO: <epoch:  3, iter:     300> l_pix: 2.0500e-01 
23-12-11 08:24:41.625 - INFO: <epoch:  4, iter:     400> l_pix: 1.5038e-01 
23-12-11 08:25:36.794 - INFO: <epoch:  5, iter:     500> l_pix: 1.1234e-01 
23-12-11 08:26:31.974 - INFO: <epoch:  6, iter:     600> l_pix: 1.0304e-01 
23-12-11 08:27:27.067 - INFO: <epoch:  7, iter:     700> l_pix: 1.3919e-01 
23-12-11 08:28:22.161 - INFO: <epoch:  8, iter:     800> l_pix: 1.3509e-01 
23-12-11 08:29:17.349 - INFO: <epoch:  9, iter:     900> l_pix: 1.1399e-01 
23-12-11 08:30:12.520 - INFO: <epoch: 10, iter:   1,000> l_pix: 1.2946e-01 
23-12-11 08:31:06.787 - INFO: <epoch: 10, iter:   1,100> l_pix: 9.0749e-02 
23-12-11 08:32:01.972 - INFO: <epoch: 11, iter:   1,200> l_pix: 1.1481e-01 
23-12-11 08:32:57.114 - INFO: <epoch: 12, iter:   1,300> l_pix: 7.5290e-02 
23-12-11 08:33:52.258 - INFO: <epoch: 13, iter:   1,400> l_pix: 8.9646e-02 
23-12-11 08:34:47.422 - INFO: <epoch: 14, iter:   1,500> l_pix: 8.0472e-02 
23-12-11 08:35:42.551 - INFO: <epoch: 15, iter:   1,600> l_pix: 1.0275e-01 
23-12-11 08:36:37.760 - INFO: <epoch: 16, iter:   1,700> l_pix: 9.8526e-02 
23-12-11 08:37:32.960 - INFO: <epoch: 17, iter:   1,800> l_pix: 8.9323e-02 
23-12-11 08:38:28.118 - INFO: <epoch: 18, iter:   1,900> l_pix: 8.0294e-02 
23-12-11 08:39:23.270 - INFO: <epoch: 19, iter:   2,000> l_pix: 7.1955e-02 
<class 'tuple'>
Traceback (most recent call last):
  File "sr.py", line 139, in <module>
    sr_img = Metrics.tensor2img(visuals['SR'])  # uint8
  File "/root/data1/shadowdiffusion/shadowdiffu_code/ShadowDiffusion-main/core/metrics.py", line 17, in tensor2img
    tensor = (tensor.squeeze().float().cpu().clamp_(*min_max))[0]  # clamp
AttributeError: 'tuple' object has no attribute 'squeeze'
root@70450fa4969e:~/data1/shadowdiffusion/shadowdiffu_code/ShadowDiffusion-main#

How can I fix it well? Thank you very much.

**Comment by GuoLanqing** [comment]
Bug has been fixed. And the ISTD pre-trained model has been released. Thanks
