### ISSUE TITLE
training time issue

### ISSUE THREAD

**Issue by cloor** [GuoLanqing/ShadowDiffusion#21]
I appreciate your research efforts. I have a keen interest in your work. I would like to retrain the model following your paper, but training for 1000 epochs on the ISTD dataset takes too long with a single GPU. Could you provide an estimate of the actual training time for reference?
Thank you!

**Comment by conutqiqi** [comment]
May I trouble the author to answer this question? I have the same question

**Comment by GuoLanqing** [comment]
Please refer to #25
