### ISSUE TITLE
About Predict

### ISSUE THREAD

**Issue by finnn00** [GuoLanqing/ShadowDiffusion#22]
If now I only have a shadow image, how can the model predict and generate the shadow-free image ?
Does the model include a mask detector?

**Comment by GuoLanqing** [comment]
This repo does not include a mask detector. But you can try to initialize the shadow mask as all-one matrix and re-train (or finetune) the model.

**Comment by 7yzx** [comment]
> If now I only have a shadow image, how can the model predict and generate the shadow-free image ? Does the model include a mask detector?

I am very sorry for asking again after so long. I want to use custom images. I saw infer.py but the sr_sr3_64_512.json mentioned in it is not provided. Thank you very much for helping me use custom images
