### ISSUE TITLE
An empty link was found in 'ISTD' checkpoints

### ISSUE THREAD

**Issue by MqLeet** [GuoLanqing/ShadowDiffusion#24]
https://github.com/GuoLanqing/ShadowDiffusion/blob/a7e7aff3028e7d7e89be0f3d3d46479dbcea00dd/README.md?plain=1#L33C96-L33C105

Hi, Lanqing @GuoLanqing, thanks for your great work!

 I found an empty link when trying to download the 'ISTD'. Was it a typo?

**Comment by GuoLanqing** [comment]
Has been updated. Thanks
