### ISSUE TITLE
Training iteration, epochs and batch_size for reproduce

### ISSUE THREAD

**Issue by cloor** [GuoLanqing/ShadowDiffusion#25]
I really interested in your work, and tried to reproduce your score.
But, in paper, you illustrate training epochs is 1000 without batch size denoted, but i cant reproduce it.
Also,  i found that there is no ckpt in ISTD datasets, and in SRD datasets file might be trained over 12,080 epochs with 2,130,000iterations...
Can you give more details for training settings for reproduce score in ISTD datasets.

**Comment by BlackJoke76** [comment]
This work is very excellent. I also have the same question，can you give more details for training settings for reproduce score in SRD datasets.

**Comment by GuoLanqing** [comment]
Sorry for replying late. Please try `batchsize=16`, `num epochs=5000`, and `lr=3e-05`. The performance will be slightly improved training more epochs. If you want to train on your customised dataset, we recommend resume the pre-trained model of SRD and fine-tune. It will be much faster.
