### ISSUE TITLE
Fail to download the pretrained model

### ISSUE THREAD

**Issue by OwalnutO** [GuoLanqing/ShadowDiffusion#6]
Hi~Thanks for your wonderful work!

However, I find that I fail to download the pretrained model, neither on the SRD nor the ISTD. Would you mind uploading them again?

**Comment by GuoLanqing** [comment]
Hi, thanks for your interest. The pretrained model for SRD has been uploaded just now. Please check again. The pretrained model for ISTD and ISTD+ will also be released soon.

**Comment by FireWallDragonDarkFluid** [comment]
Hi, any news for the ISTD and ISTD+ pretrained model?
