### ISSUE TITLE
Can you share script for generating shadow mask?

### ISSUE THREAD

**Issue by Podidiving** [GuoLanqing/ShadowDiffusion#7]
Hi :wave:

I would really like to try your model with some custom images. Can you share the script to generate mask to pass them as an input to the diffusion model?

Thanks in advance!

**Comment by GuoLanqing** [comment]
For the SRD dataset, we use the DHAN as the shadow detector. You can refer to: https://github.com/vinthony/ghost-free-shadow-removal
